### ISSUE TITLE
How does this compare with liquidautumn:meteor-useraccounts-mdl?

### ISSUE THREAD

**Issue by splendido** [meteor-useraccounts/mdl#1]
See [the package repo](https://github.com/liquidautumn/meteor-useraccounts-mdl)

**Comment by splendido** [comment]
@liquidautumn would you be willing to contribute helping @kctang to polish this out before official publish?

**Comment by liquidautumn** [comment]
@splendido I'm absolutely up to it

**Comment by splendido** [comment]
@liquidautumn, great!
I've just invited you to the [mdl team](https://github.com/orgs/meteor-useraccounts/teams/mdl) ;-)

**Comment by liquidautumn** [comment]
@splendido thank you, I'll compare code and see how can I help.

**Comment by kctang** [comment]
Awesome! Thanks guys.

@splendido any guidelines on what needs to be done before this package can be published along with the other templates?

**Comment by splendido** [comment]
@kctang nothing special, just revise it at least with a couple eyes pair and check every template has correct classes.

A crossed check of this code by @liquidautumn and the one for `liquidautumn:meteor-useraccounts-mdl` by you should be enough.

Simply discuss together what's missing (if any) and agree on how to put it.
That's it!

Let me know when you both think it's ready for publish and I'll push a new minor version.
Thank you guys!

**Comment by kctang** [comment]
I scanned through the templates, made some changes to the mdl classes used and updated the README.md.

Also did a review on `liquidautumn:meteor-useraccounts-mdl`.
- Approach is similar, to apply appropriate mdl classes
- It uses mdl-card instead of mdl-grid to specify container

I am ok to have this initial version published unless @liquidautumn has feedback on things that we should change.

Cheers!

**Comment by liquidautumn** [comment]
I agree that using mdl-card is too opinionated for common use. Seems my versoin made obsolete by @kctang code, which looks great, so I'm removing my fork and switching existing projects to meteor-useraccounts/mdl. Thanks.
I'm now moving on to React Material UI, failed to find any existing integration, so I'm going to work in the meantime. Will publish it when stabilized.

**Comment by splendido** [comment]
Sorry guys I've been away for a while...
I'm going to publish this package with the next release!

**Comment by splendido** [comment]
published!

thank you guys! this is yet another community win-win :-)
